services:
  backend:
    build: ./backend
    container_name: emotion-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: emotion-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
